FROM golang:1.23.6-alpine AS builder
WORKDIR /app
COPY . .
COPY go.mod go.mod
COPY go.sum go.sum
RUN go build -o server ./cmd/server/main.go

FROM alpine:latest
WORKDIR /app
COPY --from=builder /app/server .
USER 65532:65532
EXPOSE 8080
CMD ["/app/server"]