services:
  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - "6379:6379"

  server:
    image: server
    build:
      context: .
      dockerfile: Dockerfile.server
    env_file:
      - .env
    depends_on:
      - redis
    ports:
      - "8080:8080"
    environment:
      REDIS_HOST: redis:6379

  cli:
    image: cli
    build:
      context: .
      dockerfile: Dockerfile.cli
    environment:
      LOAD_URL: ${LOAD_URL}
      API_KEY: ${API_KEY}
      REQUESTS: ${REQUESTS}
      CONCURRENCY: ${CONCURRENCY}
    depends_on:
      - server
    entrypoint:
      - /bin/sh
      - -c
      - |
          while ! curl -4 -s -f ${LOAD_URL}; do
            echo "Waiting for server..."
            sleep 2
          done
          sleep 1

          if [ -z "${API_KEY}" ]; then
            /app/cli load -u ${LOAD_URL} -r ${REQUESTS} -c ${CONCURRENCY}
          else
            /app/cli load -u ${LOAD_URL} -a ${API_KEY} -r ${REQUESTS} -c ${CONCURRENCY}
          fi

    