FROM golang:1.23.6-alpine AS builder
WORKDIR /app
COPY . .
COPY go.mod go.mod
COPY go.sum go.sum
RUN go build -o cli ./cmd/cli/main.go

FROM alpine:latest
WORKDIR /app
RUN apk add --no-cache curl
COPY --from=builder /app/cli .
ENTRYPOINT ["/app/cli", "load"]